# Generated by Django 4.2.1 on 2023-05-04 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('rut', models.TextField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=50)),
                ('apellido', models.TextField(max_length=50)),
            ],
        ),
    ]
