# Generated by Django 4.2.1 on 2023-05-04 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcongit', '0002_alter_persona_nombre_alter_persona_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='apellido',
            field=models.CharField(max_length=50),
        ),
    ]
